/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getTeam() {
    return invoke()<Team[]>("get_team")
}

export type Branch = { id: string; title: string; history: Change[]; current_change: string }
export type Change = { id: string; message: string; context: string }
export type Team = { title: string; description: string; branches: Branch[]; current_branch: string }
